# -*- coding: utf-8 -*-
"""
AutoEncoder Training with K-Fold Cross-Validation

Modified to use the K-Fold splits generated by QuironDatasetOrganizer

@authors: debora gil, pau cano
Modified for K-Fold CV
"""

# IO Libraries
import sys
import os
import pickle

# Standard Libraries
import numpy as np
import pandas as pd
import glob

# Torch Libraries
from torch.utils.data import DataLoader
import gc
import torch
import torch.optim as optim
import torch.nn as nn

## Own Functions
from Models.AEmodels import AutoEncoderCNN
from Models.datasets import ImageDataset

# WandB (opcional)
# import wandb


def AEConfigs(Config):
    net_paramsEnc={}
    net_paramsDec={}
    inputmodule_paramsDec={}
    if Config=='1':
        # CONFIG1
        net_paramsEnc['block_configs']=[[32,32],[64,64]]
        net_paramsEnc['stride']=[[1,2],[1,2]]
        net_paramsDec['block_configs']=[[64,32],[32,3]]  # Fixed: usar 3 directamente
        net_paramsDec['stride']=net_paramsEnc['stride']
        inputmodule_paramsDec['num_input_channels']=net_paramsEnc['block_configs'][-1][-1]
        
    elif Config=='2':
        # CONFIG 2
        net_paramsEnc['block_configs']=[[32],[64],[128],[256]]
        net_paramsEnc['stride']=[[2],[2],[2],[2]]
        net_paramsDec['block_configs']=[[128],[64],[32],[3]]  # Fixed: usar 3 directamente
        net_paramsDec['stride']=net_paramsEnc['stride']
        inputmodule_paramsDec['num_input_channels']=net_paramsEnc['block_configs'][-1][-1]
        
    elif Config=='3':  
        # CONFIG3
        net_paramsEnc['block_configs']=[[32],[64],[64]]
        net_paramsEnc['stride']=[[1],[2],[2]]
        net_paramsDec['block_configs']=[[64],[32],[3]]  # Fixed: usar 3 directamente
        net_paramsDec['stride']=net_paramsEnc['stride']
        inputmodule_paramsDec['num_input_channels']=net_paramsEnc['block_configs'][-1][-1]
    
    return net_paramsEnc,net_paramsDec,inputmodule_paramsDec


def train_one_fold(fold_num, train_csv, val_csv, Config, num_epochs, batch_size, device):
    """
    Entrena el AutoEncoder para un fold específico
    
    Args:
        fold_num: Número del fold actual
        train_csv: Path al CSV de train del fold
        val_csv: Path al CSV de validación del fold
        Config: Configuración de la arquitectura
        num_epochs: Número de épocas
        batch_size: Tamaño del batch
        device: Dispositivo (cuda/cpu)
    
    Returns:
        best_val_loss: Mejor loss de validación
        model_path: Path al modelo guardado
    """
    print(f"\n{'='*70}")
    print(f"FOLD {fold_num}/{num_folds}")
    print(f"{'='*70}")
    
    # 1. Cargar datos del fold
    print(f"Cargando datos del fold {fold_num}...")
    train_dataset = ImageDataset(train_csv)
    val_dataset = ImageDataset(val_csv)
    
    print(f"  Train: {len(train_dataset)} patches (SOLO NEGATIVOS)")
    print(f"  Val:   {len(val_dataset)} patches (negativos + positivos)")
    
    # 2. Crear DataLoaders
    train_loader = DataLoader(
        train_dataset,
        batch_size=batch_size,
        shuffle=True,
        num_workers=4,
        pin_memory=True
    )
    
    val_loader = DataLoader(
        val_dataset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=4,
        pin_memory=True
    )
    
    # 3. Crear modelo
    print(f"Creando modelo para fold {fold_num}...")
    inputmodule_paramsEnc = {'num_input_channels': 3}
    net_paramsEnc, net_paramsDec, inputmodule_paramsDec = AEConfigs(Config)
    
    model = AutoEncoderCNN(
        inputmodule_paramsEnc, 
        net_paramsEnc,
        inputmodule_paramsDec, 
        net_paramsDec
    )
    model = model.to(device)
    
    # 4. Configurar entrenamiento
    criterion = nn.MSELoss()
    optimizer = optim.Adam(model.parameters(), lr=0.001)
    
    best_val_loss = float('inf')
    model_path = f'Models/AE_Config{Config}_fold{fold_num}_best.pth'
    os.makedirs('Models', exist_ok=True)
    
    # 5. Training loop
    print(f"Entrenando modelo del fold {fold_num}...")
    for epoch in range(num_epochs):
        # Training
        model.train()
        train_loss = 0.0
        
        for batch_idx, (images, _) in enumerate(train_loader):
            images = images.to(device)
            
            optimizer.zero_grad()
            outputs = model(images)
            loss = criterion(outputs, images)
            loss.backward()
            optimizer.step()
            
            train_loss += loss.item()
        
        # Validation
        model.eval()
        val_loss = 0.0
        
        with torch.no_grad():
            for images, _ in val_loader:
                images = images.to(device)
                outputs = model(images)
                loss = criterion(outputs, images)
                val_loss += loss.item()
        
        train_loss /= len(train_loader)
        val_loss /= len(val_loader)
        
        print(f'  Epoch {epoch + 1}/{num_epochs} - Train Loss: {train_loss:.4f}, Val Loss: {val_loss:.4f}')
        
        # Guardar mejor modelo
        if val_loss < best_val_loss:
            best_val_loss = val_loss
            torch.save(model.state_dict(), model_path)
            print(f'    ✓ Mejor modelo guardado (val_loss: {best_val_loss:.4f})')
    
    # Liberar memoria
    del model, optimizer
    gc.collect()
    torch.cuda.empty_cache()
    
    return best_val_loss, model_path


def evaluate_fold(fold_num, model_path, val_csv, Config, batch_size, device):
    """
    Evalúa el modelo de un fold en su conjunto de validación
    
    Args:
        fold_num: Número del fold
        model_path: Path al modelo entrenado
        val_csv: Path al CSV de validación
        Config: Configuración de la arquitectura
        batch_size: Tamaño del batch
        device: Dispositivo (cuda/cpu)
    
    Returns:
        results_df: DataFrame con errores de reconstrucción
    """
    print(f"\nEvaluando modelo del fold {fold_num}...")
    
    # 1. Cargar datos
    val_dataset = ImageDataset(val_csv)
    val_loader = DataLoader(
        val_dataset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=4
    )
    
    # 2. Cargar modelo
    inputmodule_paramsEnc = {'num_input_channels': 3}
    net_paramsEnc, net_paramsDec, inputmodule_paramsDec = AEConfigs(Config)
    
    model = AutoEncoderCNN(
        inputmodule_paramsEnc, 
        net_paramsEnc,
        inputmodule_paramsDec, 
        net_paramsDec
    )
    model.load_state_dict(torch.load(model_path))
    model = model.to(device)
    model.eval()
    
    # 3. Calcular errores de reconstrucción
    reconstruction_errors = []
    codis = []
    presences = []
    
    with torch.no_grad():
        for images, metadata in val_loader:
            images = images.to(device)
            outputs = model(images)
            
            # Error por imagen (MSE por píxel)
            errors = torch.mean((images - outputs) ** 2, dim=[1, 2, 3])
            reconstruction_errors.extend(errors.cpu().numpy())
            
            # Guardar metadata
            codis.extend(metadata['codi'])
            presences.extend(metadata['presence'])
    
    # 4. Crear DataFrame con resultados
    results_df = pd.DataFrame({
        'fold': fold_num,
        'CODI': codis,
        'presence': presences,
        'reconstruction_error': reconstruction_errors
    })
    
    # Liberar memoria
    del model
    gc.collect()
    torch.cuda.empty_cache()
    
    return results_df


######################### MAIN K-FOLD TRAINING
if __name__ == "__main__":
    
    print("="*70)
    print("AUTOENCODER K-FOLD CROSS-VALIDATION TRAINING")
    print("="*70)
    
    # 0. PARÁMETROS
    Config = '1'  # Configuración de arquitectura
    num_folds = 5
    num_epochs = 50
    batch_size = 32
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    
    # Rutas base
    DATA_SPLITS_DIR = "/export/fhome/maed01/PSIV-Detection-of-Helicobacter-pylori/data_splits"
    
    print(f"\nConfiguración:")
    print(f"  - Arquitectura: Config {Config}")
    print(f"  - Número de folds: {num_folds}")
    print(f"  - Épocas por fold: {num_epochs}")
    print(f"  - Batch size: {batch_size}")
    print(f"  - Device: {device}")
    print(f"  - Datos: {DATA_SPLITS_DIR}")
    
    # 1. ENTRENAR CADA FOLD
    fold_results = []
    
    for fold_num in range(1, num_folds + 1):
        # Rutas de los CSV del fold
        fold_dir = os.path.join(DATA_SPLITS_DIR, f"fold_{fold_num}")
        train_csv = os.path.join(fold_dir, "train_patches.csv")
        val_csv = os.path.join(fold_dir, "val_patches.csv")
        
        # Verificar que existen los archivos
        if not os.path.exists(train_csv) or not os.path.exists(val_csv):
            print(f"ERROR: No se encontraron los archivos del fold {fold_num}")
            continue
        
        # Entrenar el fold
        best_val_loss, model_path = train_one_fold(
            fold_num=fold_num,
            train_csv=train_csv,
            val_csv=val_csv,
            Config=Config,
            num_epochs=num_epochs,
            batch_size=batch_size,
            device=device
        )
        
        # Evaluar el fold
        results_df = evaluate_fold(
            fold_num=fold_num,
            model_path=model_path,
            val_csv=val_csv,
            Config=Config,
            batch_size=batch_size,
            device=device
        )
        
        # Guardar resultados del fold
        os.makedirs("Results", exist_ok=True)
        results_path = f'Results/AE_Config{Config}_fold{fold_num}_errors.csv'
        results_df.to_csv(results_path, index=False)
        
        fold_results.append({
            'fold': fold_num,
            'best_val_loss': best_val_loss,
            'model_path': model_path,
            'results_path': results_path
        })
        
        print(f"\n✓ Fold {fold_num} completado:")
        print(f"  - Mejor val_loss: {best_val_loss:.4f}")
        print(f"  - Modelo guardado en: {model_path}")
        print(f"  - Resultados guardados en: {results_path}")
    
    # 2. CONSOLIDAR RESULTADOS DE TODOS LOS FOLDS
    print("\n" + "="*70)
    print("CONSOLIDANDO RESULTADOS DE K-FOLD")
    print("="*70)
    
    # Cargar y combinar todos los resultados
    all_results = []
    for fold_info in fold_results:
        df = pd.read_csv(fold_info['results_path'])
        all_results.append(df)
    
    combined_results = pd.concat(all_results, ignore_index=True)
    combined_path = f'Results/AE_Config{Config}_kfold_all_errors.csv'
    combined_results.to_csv(combined_path, index=False)
    
    print(f"\nResultados combinados guardados en: {combined_path}")
    
    # 3. ESTADÍSTICAS GENERALES
    print("\n" + "="*70)
    print("RESUMEN DE K-FOLD CROSS-VALIDATION")
    print("="*70)
    
    # Calcular métricas por fold
    fold_summary = []
    for fold_num in range(1, num_folds + 1):
        fold_data = combined_results[combined_results['fold'] == fold_num]
        
        # Separar por presencia
        neg_errors = fold_data[fold_data['presence'] == -1]['reconstruction_error']
        pos_errors = fold_data[fold_data['presence'] == 1]['reconstruction_error']
        
        fold_summary.append({
            'fold': fold_num,
            'val_loss': fold_results[fold_num-1]['best_val_loss'],
            'neg_mean_error': neg_errors.mean(),
            'neg_std_error': neg_errors.std(),
            'pos_mean_error': pos_errors.mean(),
            'pos_std_error': pos_errors.std(),
            'separation': pos_errors.mean() - neg_errors.mean()
        })
    
    summary_df = pd.DataFrame(fold_summary)
    summary_path = f'Results/AE_Config{Config}_kfold_summary.csv'
    summary_df.to_csv(summary_path, index=False)
    
    print("\nResumen por fold:")
    print(summary_df.to_string(index=False))
    
    print(f"\nEstadísticas promedio de todos los folds:")
    print(f"  - Val Loss promedio: {summary_df['val_loss'].mean():.4f} ± {summary_df['val_loss'].std():.4f}")
    print(f"  - Error en negativos: {summary_df['neg_mean_error'].mean():.4f} ± {summary_df['neg_std_error'].mean():.4f}")
    print(f"  - Error en positivos: {summary_df['pos_mean_error'].mean():.4f} ± {summary_df['pos_std_error'].mean():.4f}")
    print(f"  - Separación promedio: {summary_df['separation'].mean():.4f}")
    
    print("\n" + "="*70)
    print("K-FOLD CROSS-VALIDATION COMPLETADO")
    print("="*70)
    print(f"\nArchivos generados:")
    print(f"  - Modelos: Models/AE_Config{Config}_fold*_best.pth")
    print(f"  - Errores por fold: Results/AE_Config{Config}_fold*_errors.csv")
    print(f"  - Errores combinados: {combined_path}")
    print(f"  - Resumen: {summary_path}")